"""HTTP DTO facade; definitions live in bounded-context packages."""

from .auth import AuthLoginRequest, AuthSignupRequest
from .billing import (
    BillingAccountCreateRequest,
    BillingAccountUpdateRequest,
    BillingAddressCreateRequest,
    BillingAddressUpdateRequest,
    ChargeCreateRequest,
    ChargeUpdateRequest,
    CouponCreateRequest,
    CouponRedemptionCreateRequest,
    CouponRedemptionUpdateRequest,
    CouponUpdateRequest,
    CreditPackageCreateRequest,
    CreditPackageUpdateRequest,
    InvoiceCreateRequest,
    InvoiceUpdateRequest,
    OrderCreateRequest,
    OrderUpdateRequest,
    PaymentMethodCreateRequest,
    PaymentMethodUpdateRequest,
    PlanCreateRequest,
    PlanItemCreateRequest,
    PlanItemUpdateRequest,
    PlanUpdateRequest,
    ProviderCustomerCreateRequest,
    ProviderDisputeCreateRequest,
    ProviderDisputeUpdateRequest,
    ProviderSubscriptionCreateRequest,
    RefundCreateRequest,
    RefundUpdateRequest,
    SubscriptionCreateRequest,
    SubscriptionUpdateRequest,
)
from .brand_color_create import BrandColorCreateRequest
from .brand_color_update import BrandColorUpdateRequest
from .content import (
    ContentCreateRequest,
    ContentUpdateRequest,
    GenerateContentRequest,
    GenerateImageRequest,
    GenerateTextRequest,
    ImproveContentRequest,
    RegenerateImageRequest,
)
from .core import (
    AssetCreateRequest,
    AssetUpdateRequest,
    BrandAssetCreateRequest,
    BrandAssetUpdateRequest,
    BrandCreateRequest,
    BrandSettingsUpdateRequest,
    BrandSettingsUpsertRequest,
    BrandUpdateRequest,
    ProjectCreateRequest,
    ProjectUpdateRequest,
    SettingsUpdateRequest,
    UserCreateRequest,
    UserUpdateRequest,
    WorkspaceCreateRequest,
    WorkspaceUpdateRequest,
)
from .design_structure_create import DesignStructureCreateRequest
from .generation import GenerationCreateRequest, GenerationUpdateRequest
from .marketing import (
    CampaignCreateRequest,
    CampaignUpdateRequest,
    PersonaCreateRequest,
    PersonaUpdateRequest,
    PlanningCreateRequest,
    PlanningUpdateRequest,
    PostStructureCreateRequest,
    PostStructureUpdateRequest,
)
from .notifications import (
    NotificationCreateRequest,
    NotificationPreferenceRequest,
    NotificationUpdateRequest,
    UserDeviceCreateRequest,
    UserDeviceUpdateRequest,
)
from .workflow import ImageWorkflowDecisionRequest, ImageWorkflowRequest
from .workspace_credit_transaction_create import WorkspaceCreditTransactionCreateRequest
from .workspace_invite_create import WorkspaceInviteCreateRequest
from .workspace_invite_update import WorkspaceInviteUpdateRequest

__all__ = [
    "AssetCreateRequest",
    "AssetUpdateRequest",
    "BillingAccountUpdateRequest",
    "BillingAddressCreateRequest",
    "BillingAddressUpdateRequest",
    "ChargeCreateRequest",
    "ChargeUpdateRequest",
    "CouponCreateRequest",
    "CouponUpdateRequest",
    "CreditPackageCreateRequest",
    "CreditPackageUpdateRequest",
    "OrderCreateRequest",
    "OrderUpdateRequest",
    "CouponRedemptionCreateRequest",
    "CouponRedemptionUpdateRequest",
    "BrandAssetCreateRequest",
    "BrandAssetUpdateRequest",
    "AuthLoginRequest",
    "AuthSignupRequest",
    "BillingAccountCreateRequest",
    "BrandCreateRequest",
    "BrandSettingsUpdateRequest",
    "BrandSettingsUpsertRequest",
    "BrandUpdateRequest",
    "CampaignCreateRequest",
    "CampaignUpdateRequest",
    "ContentCreateRequest",
    "ContentUpdateRequest",
    "GenerateContentRequest",
    "GenerateImageRequest",
    "GenerateTextRequest",
    "GenerationCreateRequest",
    "GenerationUpdateRequest",
    "ImproveContentRequest",
    "ImageWorkflowDecisionRequest",
    "ImageWorkflowRequest",
    "InvoiceCreateRequest",
    "InvoiceUpdateRequest",
    "NotificationCreateRequest",
    "NotificationUpdateRequest",
    "NotificationPreferenceRequest",
    "PersonaCreateRequest",
    "PersonaUpdateRequest",
    "PlanCreateRequest",
    "PlanItemCreateRequest",
    "PlanItemUpdateRequest",
    "PlanUpdateRequest",
    "PaymentMethodCreateRequest",
    "PaymentMethodUpdateRequest",
    "RefundCreateRequest",
    "RefundUpdateRequest",
    "ProviderDisputeCreateRequest",
    "ProviderDisputeUpdateRequest",
    "ProviderCustomerCreateRequest",
    "ProviderSubscriptionCreateRequest",
    "PlanningCreateRequest",
    "PlanningUpdateRequest",
    "PostStructureCreateRequest",
    "PostStructureUpdateRequest",
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "RegenerateImageRequest",
    "SettingsUpdateRequest",
    "SubscriptionCreateRequest",
    "SubscriptionUpdateRequest",
    "UserCreateRequest",
    "UserDeviceCreateRequest",
    "UserDeviceUpdateRequest",
    "UserUpdateRequest",
    "WorkspaceCreateRequest",
    "WorkspaceInviteCreateRequest",
    "WorkspaceInviteUpdateRequest",
    "WorkspaceCreditTransactionCreateRequest",
    "DesignStructureCreateRequest",
    "BrandColorCreateRequest",
    "BrandColorUpdateRequest",
    "WorkspaceUpdateRequest",
]
